### ISSUE TITLE
Queen's chamber

### ISSUE THREAD

**Issue by cdugeai** [jonyeezs/scoring-between-two-castles#14]
When placing queen's chamber alone in the castle, we earn 0 points instead of 1. Is it on purpose?

**Comment by jonyeezs** [comment]
Ah i think it was a very bad bug on my part. it should be 1. This happens for all sleeping rooms atm.

BTW i don't think people really use this app :laughing:. How did you find it?

**Comment by jonyeezs** [comment]
Still not working. Will need to find time to look into this.

**Comment by jonyeezs** [comment]
Should now be working

**Comment by cdugeai** [comment]
> Ah i think it was a very bad bug on my part. it should be 1. This happens for all sleeping rooms atm.
> 
> BTW i don't think people really use this app 😆. How did you find it?

I discovered the game very recently and I wanted to see if an app exists to count the score during the game. It works very well for my use. I guess, not many people have reflex to go on github to check if such an app exists but if you spread it on some *board game* websites, you could get more users !

**Comment by jonyeezs** [comment]
I did get it on reddit and boardgamegeeks ages ago. Not planning to market it again, as I hardly play this game and have other pet projects. But thanks for using it! There's a cool camera augment app in the app stores for this (but you'll have to pay for it though)
